StockApp.Front/Controllers/StockUnitController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StockApp.Front.Modals;
using System.Text.Json;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace StockApp.Front.Controllers
{
    [Authorize(Roles = "Admin,Member")]
    public class StockUnitController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public StockUnitController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        public async Task<IActionResult> List()
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync("https://localhost:7038/api/StockUnits");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<List<StockUnitListModel>>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });
                    var stockTypeList = await GetStockTypes();
                    foreach (var item in result)
                    {
                        item.StockTypeCode = stockTypeList.FirstOrDefault(x => x.Id == item.StockTypeId)?.Name;
                    }
                    return View(result);
                }
            }

            return View();
        }

        public async Task<IActionResult> Remove(Guid id)
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                var dd = await client.DeleteAsync($"https://localhost:7038/api/StockUnits/{id}");
            }

            return RedirectToAction("List");
        }
        private async Task<List<LookupModel>> GetStockTypes()
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync("https://localhost:7038/api/StockTypes");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<List<LookupModel>>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });

                    return result;
                }
            }

            return new List<LookupModel>();
        }
        public async Task<IActionResult> Create()
        {
            var stockTypeList = await GetStockTypes(); // Assuming this method returns List<StockTypeLookupModel>

            var model = new CreateStockUnitModel
            {

                StockTypeList = stockTypeList?.Select(x => new SelectListItem { Value = x.Id, Text = x.Name }).ToList() ?? new List<SelectListItem>()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateStockUnitModel model)
        {
            if (ModelState.IsValid)
            {
                var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
                if (token != null)
                {
                    var client = _httpClientFactory.CreateClient();
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);


                    var jsonData = JsonSerializer.Serialize(model);
                    var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                    var response = await client.PostAsync("https://localhost:7038/api/StockUnits", content);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("List");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Bir hata oluştu");
                    }

                }
            }
            return View(model);
        }

        public async Task<IActionResult> Get(Guid id)
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync($"https://localhost:7038/api/StockUnits/{id}");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StockUnitListModel>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });

                    return View(result);
                }
            }

            return RedirectToAction("List");
        }
        public async Task<IActionResult> Update(Guid id)
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync($"https://localhost:7038/api/StockUnits/{id}");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StockUnitListModel>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });
                    var stockTypeList = await GetStockTypes();
                    var updateModel = new StockUnitListModel
                    {
                        Id = result.Id,
                        Code = result.Code,
                        Description = result.Description,
                        Type = result.Type,
                        StockTypeId = result.StockTypeId,
                        BuyingPrice = result.BuyingPrice,
                        BuyingCurrency = result.BuyingCurrency,
                        SellingCurrency = result.SellingCurrency,
                        SellingPrice = result.SellingPrice,
                        PaperWeight = result.PaperWeight,
                        Approval = result.Approval,
                        StockTypeList = stockTypeList?.Select(x => new SelectListItem { Value = x.Id, Text = x.Name }).ToList() ?? new List<SelectListItem>(),
                    };
                    return View(result);
                }
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Update(StockUnitListModel model)
        {
            if (ModelState.IsValid)
            {
                var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
                if (token != null)
                {
                    var client = _httpClientFactory.CreateClient();
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);


                    var jsonData = JsonSerializer.Serialize(model);
                    var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                    var response = await client.PutAsync("https://localhost:7038/api/StockUnits", content);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("List");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Bir hata oluştu");
                    }

                }
            }
            return View(model);
        }
    }
}

StockApp.Front/Views/StockUnit/Create.cshtml
@model CreateStockUnitModel
@{
    Layout = "_Layout";
}

<form class="w-75 m-5 p-3  mx-auto" asp-action="Create" asp-controller="StockUnit" method="post">
    <div class="mb-3">
        <label for="@Model.Code" class="form-label">Code :</label>
        <span asp-validation-for="@Model.Code" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Code" />
    </div>
    <div class="mb-3">
        <label for="@Model.Description" class="form-label">Description :</label>
        <span asp-validation-for="@Model.Description" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Description" />
    </div>
    <div class="mb-3">
        <label for="@Model.Type" class="form-label">Type :</label>
        <span asp-validation-for="@Model.Type" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Type" />
    </div>
    <div class="mb-3">
        <label for="StockTypeId" class="form-label">Stock Type:</label>
        <span asp-validation-for="StockTypeId" class="text-danger"></span>
        <select asp-for="StockTypeId" asp-items="@Model.StockTypeList" class="form-select">
            <option value="">Select Stock Type</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="@Model.BuyingPrice" class="form-label">BuyingPrice :</label>
        <span asp-validation-for="@Model.BuyingPrice" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.BuyingPrice" />
    </div>
    <div class="mb-3">
        <label for="@Model.BuyingCurrency" class="form-label">BuyingCurrency :</label>
        <span asp-validation-for="@Model.BuyingCurrency" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.BuyingCurrency" />
    </div>
    <div class="mb-3">
        <label for="@Model.SellingPrice" class="form-label">SellingPrice :</label>
        <span asp-validation-for="@Model.SellingPrice" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.SellingPrice" />
    </div>
    <div class="mb-3">
        <label for="@Model.SellingCurrency" class="form-label">SellingCurrency :</label>
        <span asp-validation-for="@Model.SellingCurrency" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.SellingCurrency" />
    </div>
    <div class="mb-3">
        <label for="@Model.PaperWeight" class="form-label">PaperWeight :</label>
        <span asp-validation-for="@Model.PaperWeight" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.PaperWeight" />
    </div>
    <div class="mb-3">
        <label for="@Model.Approval" class="form-label">Durum :</label>
        <span asp-validation-for="@Model.Approval" class="text-danger"></span>
        <input type="checkbox" class="form-control" asp-for="@Model.Approval" />
    </div>
   
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Kayıt Oluştur</button>
        <a asp-action="List" asp-controller="StockUnit" class="btn btn-secondary">Listeye Geri Dön</a>
    </div>

    <div asp-validation-summary="ModelOnly" class="text-danger">
    </div>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

StockApp.Front/Views/StockUnit/Get.cshtml
@model StockUnitListModel
@{
    Layout = "_Layout";
}


<div class="card bg-secondary text-light">
    <h4 class="card-header">Detaylar</h4>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3">
               Id
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt class="col-sm-3">
               Code
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Code)
            </dd>
            <dt class="col-sm-3">
               Description
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-3">
               Type
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Type)   
            </dd>
            <dt class="col-sm-3">
                StockTypeId
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.StockTypeId)
            </dd>
            <dt class="col-sm-3">
               BuyingPrice
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.BuyingPrice)    
            </dd>
            <dt class="col-sm-3">
                BuyingCurrency
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.BuyingCurrency)
            </dd>
            <dt class="col-sm-3">
               SellingPrice
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.SellingPrice)    
            </dd>
            <dt class="col-sm-3">
               SellingCurrency
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.SellingCurrency)
            </dd>
            <dt class="col-sm-3">
                PaperWeight
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.PaperWeight)     
            </dd>
            <dt class="col-sm-3">
                Approval
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Approval)
            </dd>
        </dl>
    </div>
    <div class="card-footer">
        <a asp-action="Update" asp-route-id="@Model?.Id" class="btn btn-primary">Düzenle</a> |
        <a asp-action="List" class="btn btn-secondary">Listeye Geri Dön</a>
    </div>
</div>

StockApp.Front/Views/StockUnit/List.cshtml
@model List<StockUnitListModel>
@{
    Layout = "_Layout";
}

@{

    <div class="text-end ">
        <a asp-action="Create" class="btn btn-primary btn-sm" asp-controller="StockUnit">Yeni Kayıt Oluştur</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Code</th>
                <th>Description</th>
                <th>Type</th>
                <th>StockTypeId</th>
                <th>BuyingPrice</th>
                <th>BuyingCurrency</th>
                <th>SellingPrice</th>
                <th>SellingCurrency</th>
                <th>PaperWeight</th>
                <th>Approval</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var stockUnit in Model)
            {
                <tr>
                    <td>@stockUnit.Id</td>
                    <td>@stockUnit.Code</td>
                    <td>@stockUnit.Description</td>
                    <td>@stockUnit.Type</td>
                    <td>@stockUnit.StockTypeId</td>
                    <td>@stockUnit.BuyingPrice</td>
                    <td>@stockUnit.BuyingCurrency</td>
                    <td>@stockUnit.SellingPrice</td>
                    <td>@stockUnit.SellingCurrency</td>
                    <td>@stockUnit.PaperWeight</td>
                    <td>@stockUnit.Approval</td>

                    <td>
                        <a asp-action="Update" asp-controller="StockUnit" asp-route-id="@stockUnit.Id" class="btn btn-warning btn-sm">Update</a>
                        <a asp-action="Remove" asp-controller="StockUnit" asp-route-id="@stockUnit.Id" class="btn btn-danger btn-sm">Sil</a>
                        <a asp-action="Get" asp-controller="StockUnit" asp-route-id="@stockUnit.Id" class="btn btn-danger btn-sm">Detay</a>
                    </td>
                </tr>
            }

        </tbody>
    </table>

}

StockApp.Front/Views/StockUnit/Update.cshtml
@model StockUnitListModel
@{
    Layout = "_Layout";
}

<form class="w-75 m-5 p-3  mx-auto" asp-action="Update" asp-controller="StockUnit" method="post">
    <input type="hidden" asp-for="@Model.Id" />

    <div class="mb-3">
        <label for="@Model.Code" class="form-label">Code :</label>
        <span asp-validation-for="@Model.Code" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Code" />
    </div>
    <div class="mb-3">
        <label for="@Model.Description" class="form-label">Description :</label>
        <span asp-validation-for="@Model.Description" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Description" />
    </div>
    <div class="mb-3">
        <label for="@Model.Type" class="form-label">Type :</label>
        <span asp-validation-for="@Model.Type" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Type" />
    </div>
    <div class="mb-3">
        <label for="StockTypeId" class="form-label">Stock Type:</label>
        <span asp-validation-for="StockTypeId" class="text-danger"></span>
        <select asp-for="StockTypeId" asp-items="@Model.StockTypeList" class="form-select">
            <option value="">Select Stock Type</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="@Model.BuyingPrice" class="form-label">BuyingPrice :</label>
        <span asp-validation-for="@Model.BuyingPrice" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.BuyingPrice" />
    </div>
    <div class="mb-3">
        <label for="@Model.BuyingCurrency" class="form-label">BuyingCurrency :</label>
        <span asp-validation-for="@Model.BuyingCurrency" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.BuyingCurrency" />
    </div>
    <div class="mb-3">
        <label for="@Model.SellingPrice" class="form-label">SellingPrice :</label>
        <span asp-validation-for="@Model.SellingPrice" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.SellingPrice" />
    </div>
    <div class="mb-3">
        <label for="@Model.SellingCurrency" class="form-label">SellingCurrency :</label>
        <span asp-validation-for="@Model.SellingCurrency" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.SellingCurrency" />
    </div>
    <div class="mb-3">
        <label for="@Model.PaperWeight" class="form-label">PaperWeight :</label>
        <span asp-validation-for="@Model.PaperWeight" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.PaperWeight" />
    </div>
    <div class="mb-3">
        <label for="@Model.Approval" class="form-label">Durum :</label>
        <span asp-validation-for="@Model.Approval" class="text-danger"></span>
        <input type="checkbox" class="form-control" asp-for="@Model.Approval" />
    </div>
   


    <div class="mb-3">
        <button class="btn btn-primary w-100">Kaydet</button>
        <a asp-action="List" asp-controller="StockUnit" class="btn btn-secondary">Listeye Geri Dön</a>

    </div>

    <div asp-validation-summary="ModelOnly" class="text-danger">
    </div>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}