StockApp.Front/Controllers/StockTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using System.Text.Json;
using System.Text;
using StockApp.Front.Modals;

namespace StockApp.Front.Controllers
{
    [Authorize(Roles = "Admin,Member")]
    public class StockTypeController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public StockTypeController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        public async Task<IActionResult> List()
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync("https://localhost:7038/api/StockTypes");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<List<StockTypeListModel>>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });

                    return View(result);
                }
            }

            return View();
        }
        public async Task<IActionResult> Get(Guid id)
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync($"https://localhost:7038/api/StockTypes/{id}");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StockTypeListModel>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });

                    return View(result);
                }
            }

            return RedirectToAction("List");
        }
        public async Task<IActionResult> Remove(Guid id)
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
              var dd=  await client.DeleteAsync($"https://localhost:7038/api/StockTypes/{id}");
            }

            return RedirectToAction("List");
        }

        public IActionResult Create()
        {
            return View(new CreateStockTypeModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateStockTypeModel model)
        {
            if (ModelState.IsValid)
            {
                var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
                if (token != null)
                {
                    var client = _httpClientFactory.CreateClient();
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);


                    var jsonData = JsonSerializer.Serialize(model);
                    var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                    var response = await client.PostAsync("https://localhost:7038/api/StockTypes", content);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("List");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Bir hata oluştu");
                    }

                }
            }
            return View(model);
        }


        public async Task<IActionResult> Update(Guid id)
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync($"https://localhost:7038/api/StockTypes/{id}");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StockTypeListModel>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });

                    return View(result);
                }
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Update(StockTypeListModel model)
        {
            if (ModelState.IsValid)
            {
                var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
                if (token != null)
                {
                    var client = _httpClientFactory.CreateClient();
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);


                    var jsonData = JsonSerializer.Serialize(model);
                    var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                    var response = await client.PutAsync("https://localhost:7038/api/StockTypes", content);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("List");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Bir hata oluştu");
                    }

                }
            }
            return View(model);
        }
    }
}

StockApp.Front/Views/StockType/Create.cshtml
@model CreateStockTypeModel
@{
    Layout = "_Layout";
}

<br />
<br />
<br />

<div class="container-fluid" style="padding-left: 300px; padding-right: 300px;">
    <div class="card bg-dark text-light">
        <h4 class="card-header">Yeni Kayıt</h4>
        @foreach (var modelState in ViewData.ModelState.Values)
        {
            foreach (var error in modelState.Errors)
            {
                <div class="alert alert-danger">@error.ErrorMessage</div>
            }
        }
        <div class="card-body">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Name" class="control-label">Ad</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Approval" class="control-label">Approval</label>
                    <input asp-for="Approval" class="form-control" />
                    <span asp-validation-for="Approval" class="checkbox-danger"></span>
                </div>
                <br />
              
                <br />
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Kayıt Oluştur</button>
                    <a asp-action="List" class="btn btn-secondary">Listeye Geri Dön</a>
                </div>
            </form>
        </div>
    </div>
</div>
<br />
<br />
<br />



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

StockApp.Front/Views/StockType/Get.cshtml
@model StockTypeListModel
@{
    Layout = "_Layout";
}


<div class="card bg-secondary text-light">
    <h4 class="card-header">Detaylar</h4>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3">
                Id
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt class="col-sm-3">
                Name
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Name)
            </dd>
         
            <dt class="col-sm-3">
                Approval
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Approval)
            </dd>
        </dl>
    </div>
    <div class="card-footer">
        <a asp-action="Update" asp-route-id="@Model?.Id" class="btn btn-primary">Düzenle</a> |
        <a asp-action="List" class="btn btn-secondary">Listeye Geri Dön</a>
    </div>
</div>

StockApp.Front/Views/StockType/List.cshtml
@model List<StockTypeListModel>
@{
    Layout = "_Layout";
}



    <div id="loadingAnimation" class="loading-animation"></div>
    <br />
    <p>
        <a asp-action="Create" style="color: white; padding: 8px 16px; background-color: #007bff; border: 1px solid #007bff; border-radius: 4px; text-decoration: none;">Yeni Kayıt</a>
    </p>
    <table id="dataTable" class="table" style="width: 80%; height:90%; border-collapse: collapse; margin-bottom: 1rem; color: #000;">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Name</td>
                    <td>Approval</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var stockType in Model)
                {
                    <tr>
                        <td>
                            @stockType.Id

                        </td>
                        <td>
                            @stockType.Name
                        </td>
                        <td>
                            @stockType.Approval
                        </td>
                       
                        <td>
                            <a asp-action="Update" asp-controller="StockType" asp-route-id="@stockType.Id" class="btn btn-warning btn-sm">Update</a>
                    <a asp-action="Remove" asp-controller="StockType" asp-route-id="@stockType.Id" class="btn btn-danger btn-sm">Sil</a>
                        <a asp-action="Get" asp-controller="StockType" asp-route-id="@stockType.Id" class="btn btn-danger btn-sm">Detay</a>

                        </td>
                    </tr>
                }

            </tbody>
        </table>
   
    <div id="pagination" class="pagination" style="font-weight: bold; font-size: 20px; color: black;"></div>
@section Scripts {
    <script>
        document.onreadystatechange = function () {
            if (document.readyState === 'complete') {
                // Yükleme tamamlandığında loading animasyonunu
                setTimeout(function () {
                    document.getElementById('loadingAnimation').style.display = 'none';
                }, 1500);
            }
        };
        var data = @Html.Raw(Json.Serialize(Model));

        document.addEventListener("DOMContentLoaded", function () {
            const inputs = document.querySelectorAll('input[type="text"]');
            inputs.forEach(input => {
                input.addEventListener('input', function (e) {
                    filterTable(input.name);
                });
            });
        });

      



        const itemsPerPage = 5;
        let currentPage = 1;

        function displayTable(currentPage) {
            const tableBody = document.getElementById('tableBody');
            tableBody.innerHTML = '';

            const startIndex = (currentPage - 1) * itemsPerPage;
            const endIndex = startIndex + itemsPerPage;
            const paginatedData = data.slice(startIndex, endIndex);

            paginatedData.forEach(item => {
                const row = document.createElement('tr');
                row.innerHTML = `
                                           <td>${item.id}</td>
                                                <td>${item.name}</td>
                                        <td>${item.approval}</td>
                                        <td>
                                                    <a href="StockType/Update/${item.id}" class="btn btn-secondary">Düzenle</a>
                                                    <a href="StockType/Get/${item.id}" class="btn btn-info">Detay</a>
                                                    <a href="StockType/Remove/${item.id}" class="btn btn-danger">Sil</a>
                                        </td>
                                `;
                tableBody.appendChild(row);
            });
        }

        function displayPagination() {
            const pagination = document.getElementById('pagination');
            pagination.innerHTML = '';

            const pageCount = Math.ceil(data.length / itemsPerPage);
            for (let i = 1; i <= pageCount; i++) {
                const link = document.createElement('a');
                link.href = '#';
                link.textContent = i;
                link.addEventListener('click', function () {
                    currentPage = i;
                    displayTable(currentPage);
                });
                pagination.appendChild(link);
            }
        }

        displayTable(currentPage);
        displayPagination();
    </script>
}

StockApp.Front/Views/StockType/Remove.cshtml
@model StockTypeListModel
@{
    Layout = "_Layout";
}

<div class="card bg-secondary text-light">
    <h4 class="card-header">Veri Silme Ekranı</h4>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3">
                Ad
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-3">
                Approval
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Approval)
            </dd>
           
        </dl>
    </div>
    <div class="card-footer">
        <form asp-action="Remove">
            <input type="hidden" asp-for="Id" />
            <button type="submit" class="btn btn-danger">Sil</button>
            <a asp-action="List" class="btn btn-secondary">Ana Sayfa</a>
        </form>
    </div>
</div>

StockApp.Front/Views/StockType/Update.cshtml
@model StockTypeListModel
@{
    Layout = "_Layout";
}

<br />
<br />
<br />
<div class="container" style="padding-left: 50px; padding-right: 50px;">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Update">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Name" class="control-label">Ad</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Approval" class="control-label">Approval</label>
                    <input asp-for="Approval" class="form-control" />
                    <span asp-validation-for="Approval" class="text-danger"></span>
                </div>
                <br />
              
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Kaydet</button>
                    <a asp-action="List" class="btn btn-secondary">Listeye Geri Dön</a>
                </div>
            </form>
        </div>
    </div>

</div>
<br />
<br />
<br />
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}