StockApp.Front/Controllers/StockCardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Text;
using StockApp.Front.Modals;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace StockApp.Front.Controllers
{
    [Authorize(Roles = "Admin,Member")]
    public class StockCardController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public StockCardController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        public async Task<IActionResult> List()
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync("https://localhost:7038/api/StockCards");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<List<StockCardListModel>>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });

                    // Retrieve lookup data
                    var stockTypeList = await GetStockTypes();
                    var stockUnitList = await GetStockUnits();

                    // Update each item in the result list with lookup data
                    foreach (var item in result)
                    {
                        item.StockTypeCode = stockTypeList.FirstOrDefault(x => x.Id == item.StockTypeId)?.Name;
                        item.StockUnitDescription = stockUnitList.FirstOrDefault(x => x.Id == item.StockUnitId)?.Description;
                    }

                    return View(result);
                }
            }

            return View();
        }

        public async Task<IActionResult> Get(Guid id)
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync($"https://localhost:7038/api/StockCards/{id}");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StockCardListModel>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });

                    return View(result);
                }
            }

            return RedirectToAction("List");
        }
        public async Task<IActionResult> Remove(Guid id)
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                var dd = await client.DeleteAsync($"https://localhost:7038/api/StockCards/{id}");
            }

            return RedirectToAction("List");
        }

        private async Task<List<LookupModel>> GetStockTypes()
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync("https://localhost:7038/api/StockTypes");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<List<LookupModel>>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });

                    return result;
                }
            }

            return new List<LookupModel>();
        }
        private async Task<List<LookupModel>> GetStockUnits()
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync("https://localhost:7038/api/StockUnits");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<List<LookupModel>>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });

                    return result;
                }
            }

            return new List<LookupModel>();
        }
        public async Task<IActionResult> Create()
        {
            var stockTypeList = await GetStockTypes(); // Assuming this method returns List<StockTypeLookupModel>
            var stockUnitList = await GetStockUnits(); // Assuming this method returns List<StockTypeLookupModel>
           
           var model = new CreateStockCardModel
            {
               
               StockTypeList = stockTypeList?.Select(x => new SelectListItem { Value = x.Id, Text = x.Name }).ToList() ?? new List<SelectListItem>(),
         StockUnitList=stockUnitList?.Select(x => new SelectListItem { Value = x.Id, Text = x.Description }).ToList() ?? new List<SelectListItem>()
           };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateStockCardModel model)
        {
            if (ModelState.IsValid)
            {
                var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
                if (token != null)
                {
                    var client = _httpClientFactory.CreateClient();
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);


                    var jsonData = JsonSerializer.Serialize(model);
                    var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                    var response = await client.PostAsync("https://localhost:7038/api/StockCards", content);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("List");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Bir hata oluştu");
                    }

                }
            }
            return View(model);
        }


        public async Task<IActionResult> Update(Guid id)
        {
            var token = User.Claims.FirstOrDefault(x => x.Type == "accesToken")?.Value;
            if (token != null)
            {
                var client = _httpClientFactory.CreateClient();
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await client.GetAsync($"https://localhost:7038/api/StockCards/{id}");

                if (response.IsSuccessStatusCode)
                {
                    var jsonData = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<StockCardListModel>(jsonData, new JsonSerializerOptions
                    {
                        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                    });

                    // Retrieve lookup data
                    var stockTypeList = await GetStockTypes();
                    var stockUnitList = await GetStockUnits();

                    // Create the update model and populate lookup lists
                    var updateModel = new StockCardListModel
                    {
                        Id = result.Id,
                        Code = result.Code,
                        ProductType = result.ProductType,
                        Description = result.Description,
                        StockTypeId = result.StockTypeId,
                        StockUnitId = result.StockUnitId,
                        ShelfInformation = result.ShelfInformation,
                        CabinetInformation = result.CabinetInformation,
                        Amount = result.Amount,
                        CriticalQuantity = result.CriticalQuantity,
                        StockTypeList = stockTypeList?.Select(x => new SelectListItem { Value = x.Id, Text = x.Name }).ToList() ?? new List<SelectListItem>(),
                        StockUnitList = stockUnitList?.Select(x => new SelectListItem { Value = x.Id, Text = x.Description }).ToList() ?? new List<SelectListItem>()
                    };

                    return View(updateModel);
                }
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Update(StockCardListModel model)
        {
            if (ModelState.IsValid)
            {

StockApp.Front/Views/StockCard/Create.cshtml
@model CreateStockCardModel
@{
    Layout = "_Layout";
}

<form class="w-75 m-5 p-3  mx-auto" asp-action="Create" asp-controller="StockCard" method="post">
    <div class="mb-3">
        <label for="@Model.Code" class="form-label">Code :</label>
        <span asp-validation-for="@Model.Code" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Code" />
    </div>
    <div class="mb-3">
        <label for="@Model.ProductType" class="form-label">ProductType :</label>
        <span asp-validation-for="@Model.ProductType" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.ProductType" />
    </div>
    <div class="mb-3">
        <label for="@Model.Description" class="form-label">Description :</label>
        <span asp-validation-for="@Model.Description" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Description" />
    </div>
    <div class="mb-3">
        <label for="StockTypeId" class="form-label">Stock Type:</label>
        <span asp-validation-for="StockTypeId" class="text-danger"></span>
        <select asp-for="StockTypeId" asp-items="@Model.StockTypeList" class="form-select">
            <option value="">Select Stock Type</option>
        </select>
    </div> 
    <div class="mb-3">
        <label for="StockUnitId" class="form-label">Stock Unit:</label>
        <span asp-validation-for="StockUnitId" class="text-danger"></span>
        <select asp-for="StockUnitId" asp-items="@Model.StockUnitList" class="form-select">
            <option value="">Select Stock Unit</option>
        </select>
    </div>
 
    <div class="mb-3">
        <label for="@Model.ShelfInformation" class="form-label">ShelfInformation :</label>
        <span asp-validation-for="@Model.ShelfInformation" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.ShelfInformation" />
    </div>
    <div class="mb-3">
        <label for="@Model.CabinetInformation" class="form-label">CabinetInformation :</label>
        <span asp-validation-for="@Model.CabinetInformation" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.CabinetInformation" />
    </div>
    <div class="mb-3">
        <label for="@Model.Amount" class="form-label">Amount :</label>
        <span asp-validation-for="@Model.Amount" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Amount" />
    </div>
    <div class="mb-3">
        <label for="@Model.CriticalQuantity" class="form-label">CriticalQuantity :</label>
        <span asp-validation-for="@Model.CriticalQuantity" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.CriticalQuantity" />
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Kayıt Oluştur</button>
        <a asp-action="List" asp-controller="StockCard" class="btn btn-secondary">Listeye Geri Dön</a>
    </div>

    <div asp-validation-summary="ModelOnly" class="text-danger">
    </div>
</form>

StockApp.Front/Views/StockCard/List.cshtml
@model List<StockCardListModel>
@{
    Layout = "_Layout";
}

@{

    <div class="text-end">
        <a asp-action="Create" class="btn btn-primary btn-sm" asp-controller="StockCard">Yeni Kayıt Oluştur</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <td>Id</td>
                <td>Code</td>
                <td>ProductType</td>
                <td>Description</td>
                <td>StockTypeId</td>
                // <td>StockTypeName</td>
                <td>StockUnitId</td>
                // <td>StockUnitDescription</td>
                <td>ShelfInformation</td>
                <td>CabinetInformation</td>
                <td>Amount</td>
                <td>CriticalQuantity</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var stockCard in Model)
            {
                <tr>
                    <td>
                        @stockCard.Id

                    </td>
                    <td>
                        @stockCard.Code
                    </td>
                    <td>
                        @stockCard.ProductType
                    </td>
                    <td>
                        @stockCard.Description
                    </td>
                    <td>
                        @stockCard.StockTypeId
                    </td>
                    <td>
                        @stockCard.StockTypeCode
                    </td>
                    <td>
                        @stockCard.StockUnitId
                    </td>
                    <td>
                        @stockCard.StockUnitDescription
                    </td>
                    <td>
                        @stockCard.ShelfInformation
                    </td>
                    <td>
                        @stockCard.CabinetInformation
                    </td>
                    <td>
                        @stockCard.Amount
                    </td>
                    <td>
                        @stockCard.CriticalQuantity
                    </td>
                    <td>
                        <a asp-action="Update" asp-controller="StockCard" asp-route-id="@stockCard.Id" class="btn btn-warning btn-sm">Update</a>
                        <a asp-action="Remove" asp-controller="StockCard" asp-route-id="@stockCard.Id" class="btn btn-danger btn-sm">Sil</a>
                    </td>
                </tr>
            }

        </tbody>
    </table>

}

StockApp.Front/Views/StockCard/Update.cshtml
@model StockCardListModel
@{
    Layout = "_Layout";
}

<form class="w-75 m-5 p-3  mx-auto" asp-action="Update" asp-controller="StockCard" method="post">
    <input type="hidden" asp-for="@Model.Id" />

    <div class="mb-3">
        <label for="@Model.Code" class="form-label">Code :</label>
        <span asp-validation-for="@Model.Code" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Code" />
    </div>
    <div class="mb-3">
        <label for="@Model.ProductType" class="form-label">ProductType :</label>
        <span asp-validation-for="@Model.ProductType" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.ProductType" />
    </div>
    <div class="mb-3">
        <label for="@Model.Description" class="form-label">Description :</label>
        <span asp-validation-for="@Model.Description" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Description" />
    </div>
     <div class="mb-3">
        <label for="StockTypeId" class="form-label">Stock Type:</label>
        <span asp-validation-for="StockTypeId" class="text-danger"></span>
        <select asp-for="StockTypeId" asp-items="@Model.StockTypeList" class="form-select">
            <option value="">Select Stock Type</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="StockUnitId" class="form-label">Stock Unit:</label>
        <span asp-validation-for="StockTypeId" class="text-danger"></span>
        <select asp-for="StockUnitId" asp-items="@Model.StockUnitList" class="form-select">
            <option value="">Select Stock Unit</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="@Model.ShelfInformation" class="form-label">ShelfInformation :</label>
        <span asp-validation-for="@Model.ShelfInformation" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.ShelfInformation" />
    </div>
    <div class="mb-3">
        <label for="@Model.CabinetInformation" class="form-label">CabinetInformation :</label>
        <span asp-validation-for="@Model.CabinetInformation" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.CabinetInformation" />
    </div>
    <div class="mb-3">
        <label for="@Model.Amount" class="form-label">Amount :</label>
        <span asp-validation-for="@Model.Amount" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.Amount" />
    </div>
    <div class="mb-3">
        <label for="@Model.CriticalQuantity" class="form-label">CriticalQuantity :</label>
        <span asp-validation-for="@Model.CriticalQuantity" class="text-danger"></span>
        <input type="text" class="form-control" asp-for="@Model.CriticalQuantity" />
    </div>
    <div class="mb-3">
        <button class="btn btn-primary w-100">Kaydet</button>
        <a asp-action="List" asp-controller="StockCard" class="btn btn-secondary">Listeye Geri Dön</a>

    </div>

    <div asp-validation-summary="ModelOnly" class="text-danger">
    </div>
</form>